### PR TITLE
Added new --confirm/-c argument when deleting users to bypass prompt

### PR DESCRIPTION
**Pull request by KaibutsuX**

### CODE REVIEW

**Review by kolaente — CHANGES_REQUESTED** [review]
Please fix the lint issues (run `mage check:golangci-fix`).

**Comment by KaibutsuX** [comment]
FYI, `golangci-lint run --fix` exited 1 with:
```
INFO [runner] linters took 12.545000771s with stages: goanalysis_metalinter: 12.474141491s 
pkg/routes/caldav/listStorageProvider.go:177:19: G601: Implicit memory aliasing in for loop. (gosec)
				task:         &t.Task,
				              ^
pkg/routes/caldav/listStorageProvider.go:180:37: G601: Implicit memory aliasing in for loop. (gosec)
			r := data.NewResource(getTaskURL(&t.Task), &rr)
			                                 ^
pkg/routes/caldav/listStorageProvider.go:414:23: G601: Implicit memory aliasing in for loop. (gosec)
		labelMap[l.Title] = &l.Label
		                    ^
```

**Comment by kolaente** [comment]
Which golangci-lint version are you using?

**Comment by KaibutsuX** [comment]
> Which golangci-lint version are you using?

`golangci-lint has version v1.54.2 built with go1.21.1 from (unknown, mod sum: "h1:oR9zxfWYxt7hFqk6+fw6Enr+E7F0SN2nqHhJYyIb0yo=") on (unknown)`

**Comment by kolaente** [comment]
Rebase and try again

**Comment by KaibutsuX** [comment]
Seems rebase resolved the linter issue

**Review by kolaente — APPROVED** [review]

**Pull request merged**
